# Ejemplo 4. Valores y vectores propios 

Si el tensor de esfuerzos en un punto $P$, en el sistema de referencia $X,Y,Z$ está definidido por:

$$\begin{align*}
\\
&\sigma_{xx} = 200\dfrac{kgf}{cm^2}; \;\;\; \sigma_{yy} =0\dfrac{kgf}{cm^2}; \;\;\; \sigma_{zz} = 0\dfrac{kgf}{cm^2} \\\\
&\tau_{xy} = \tau_{yx} =100\dfrac{kgf}{cm^2}, \;\;\; \tau_{xz} = \tau_{zx} =300\dfrac{kgf}{cm^2}; \;\;\;\tau_{yz} = \tau_{zy} = 0 \dfrac{kgf}{cm^2}\\\\
\end{align*}$$

<img src="./img/Sorigen.png" alt="Estado de esfuerzos." style="width:300px">


* Determine los valores y direcciones principales:



## Solución:

Inicialmente encontremos los valores principales $(\lambda)$ a partir de la solución del polinomio característico: 

${\lambda ^3} - {I_\sigma}{\lambda ^2} + {II_\sigma}\lambda  - {III_\sigma} = 0$

Donde ${I_\sigma}$, ${II_\sigma}$ y ${III_\sigma}$ son los invariantes 1, 2 y 3 respectivamente que están dados por: 

${I_\sigma } = {\sigma _{xx}} + {\sigma _{yy}} + {\sigma _{zz}}$

${II_\sigma } = {\sigma _{xx}}{\sigma _{yy}} + {\sigma _{xx}}{\sigma _{zz}} + {\sigma _{zz}}{\sigma _{yy}} - \tau _{xy}^2 - \tau _{xz}^2 - \tau _{yz}^2$

${III_\sigma } = {\sigma _{xx}}{\sigma _{yy}}{\sigma _{zz}} + 2{\tau _{xy}}{\tau _{xz}}{\tau _{yz}} - {\sigma _{xx}}\tau _{yz}^2 - {\sigma _{yy}}\tau _{xz}^2 - {\sigma _{zz}}\tau _{xy}^2$

In [1]:
from __future__ import division, print_function
import numpy as np
from scipy import linalg

S = np.array([
    [200,100,300.],
    [100,0,0],
    [300,0,0]])

IS   = S[0,0]+S[1,1]+S[2,2]
IIS  = S[0,0]*S[1,1]+S[1,1]*S[2,2]+S[0,0]*S[2,2]-(S[0,1]**2)-(S[0,2]**2)-(S[1,2]**2)
IIIS = S[0,0]*S[1,1]*S[2,2]-S[0,0]*(S[1,2]**2)-S[1,1]*(S[0,2]**2)-S[2,2]*(S[0,1]**2)+2*S[1,2]*S[0,2]*S[0,1]


print('Invariantes: {}, {}, {}'.format(IS,IIS,IIIS))
 

Invariantes: 200.0, -100000.0, 0.0


## Resolviendo usando el polinomio característico:

In [2]:
coeff = [1.0,-IS,IIS,-IIIS]
ps=np.roots(coeff)

print("Esfuerzos principales: {}".format(np.sort(np.round(ps, 1))))

Esfuerzos principales: [-231.7    0.   431.7]


## Resolviendo usando librerías de Python

Usando ``linalg.eig`` podemos encontrar valores (``vals``) y direcciones
principales (``dirs``) simultaneamente


In [3]:
vals, dirs = linalg.eigh(S)

print("Esfuerzos principales: {}".format(vals))

Esfuerzos principales: [-231.66247904    0.          431.66247904]


In [4]:
print('n= {}'.format(dirs))

n= [[ 0.59096897  0.          0.80669429]
 [-0.25509913 -0.9486833   0.1868808 ]
 [-0.7652974   0.31622777  0.56064239]]


De esta manera escribamos el tensor asociado a las direcciones principales: 

In [5]:
Sp = np.diag(vals)


print('Sp = {}'.format(Sp))



Sp = [[-231.66247904    0.            0.        ]
 [   0.            0.            0.        ]
 [   0.            0.          431.66247904]]


Que graficamente es
<img src="./img/Sprinc.png" alt="Estado de esfuerzos." style="width:400px">

Los vectores $i'$, $j'$ y $k'$ están dados por:

In [6]:
print("i' = {}".format(dirs[:, 0]))
print("j' = {}".format(dirs[:, 1]))
print("k' = {}".format(dirs[:, 2]))

i' = [ 0.59096897 -0.25509913 -0.7652974 ]
j' = [ 0.         -0.9486833   0.31622777]
k' = [ 0.80669429  0.1868808   0.56064239]



Verifiquemos que se cumplen los invariantes en el tensor asociado a direcciones principales:

In [7]:
IS  = Sp[0,0]+Sp[1,1]+Sp[2,2]
IIS  = Sp[0,0]*Sp[1,1]+Sp[1,1]*Sp[2,2]+Sp[0,0]*Sp[2,2]-(Sp[0,1]**2)-(Sp[0,2]**2)-(Sp[1,2]**2)
IIIS = Sp[0,0]*Sp[1,1]*Sp[2,2]-Sp[0,0]*(Sp[1,2]**2)-Sp[1,1]*(Sp[0,2]**2)-Sp[2,2]*(Sp[0,1]**2)+2*Sp[1,2]*Sp[0,2]*Sp[0,1]

print('Invariantes: {}, {}, {}'.format(IS,IIS,IIIS))

Invariantes: 200.0, -100000.0, 0.0


Para terminar se debe de tener en cuenta que las direcciones principales no son otra cosa que la matriz de cosenos directores que transformaría el tensor original al tensor en direcciones principales mediante la ecuación de transformación: 

\begin{align}
&[\sigma']=[C][\sigma][C]^T\\
\end{align}

Teniendo en cuenta que n es dado por vectores columna entonces la matriz de cosenos directores está dada por:

\begin{align}
&[C] = [n]^T
\end{align}



In [8]:
C = dirs.T
Sp2 = np.dot(np.dot(C,S),C.T)


print('Sp = {}'.format(np.round(Sp2, 2)))

Sp = [[-231.66   -0.      0.  ]
 [  -0.      0.     -0.  ]
 [   0.     -0.    431.66]]


In [9]:
from IPython.core.display import HTML
def css_styling():
    styles = open('./custom_barba.css', 'r').read()
    return HTML(styles)
css_styling()